version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "applicatie-basis"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ghvaajc0i25f"
s3_prefix = "applicatie-basis"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
