AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  multi-step component 1

Resources:
  StockCheckerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/stock_checker/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64

  StockSellerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/stock_seller/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64

  StockBuyerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/stock_buyer/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64

Outputs:
  StockCheckerFunctionArn:
    Description: "Stock Checker Function ARN"
    Value: !GetAtt StockCheckerFunction.Arn
    Export:
      Name: StockCheckerFunctionArn

  StockCheckerFunctionArnRole:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - StockCheckerFunctionRole
      - Arn

  StockSellerFunctionArn:
    Description: "Stock Seller Function ARN"
    Value: !GetAtt StockSellerFunction.Arn
    Export:
      Name: StockSellerFunctionArn

  StockBuyerFunctionArn:
    Description: "Stock Buyer Function ARN"
    Value: !GetAtt StockBuyerFunction.Arn
    Export:
      Name: StockBuyerFunctionArn
